{
    project: "dialogue-summarization",
    log_id: "version_1",
    model_name: "hyunwoongko/kobart",
    # train_data_path: "../datasets/개인및관계.json",
    # valid_data_path: "../datasets/개인및관계_dev.json",

    finetune: false,
    finetune_path: "hyunwoongko/kobart",
    separator: "<unused1>",
    meta_sep: "<unused2>",
    batch_size: 64,
    accumulate_grad_batches: 1,
    lr: 3e-5,
    weight_decay: 3e-7,
    num_warmup_steps: 0.1,
    num_training_steps: 20000,
    max_length: 300,  ## len
    strategy: "cut",
    save_path: "../saved/",
    save_monitor: "valid_loss",
    save_mode: "min",
    num_save_ckpt: 5,
    trainer_args: {
        gpus: 1,
        accelerator: "ddp",
        precision: 16,
        val_check_interval: 1.0,
        gradient_clip_val: 1.0,
    },
    deepspeed: {
        train_batch_size: "auto",
        fp16: {
            enabled: true,
            "initial_scale_power": 16,
            "loss_scale_window": 1000,
            "hysteresis": 2,
            "min_loss_scale": 1
        },
        zero_optimization: {
            stage: 3,
            allgather_partitions: true,
            allgather_bucket_size: 2e8,
            overlap_comm: true,
            reduce_scatter: true,
            reduce_bucket_size: 2e8,
            contiguous_gradients: true,
            offload_optimizer: {
                device: "cpu",
                pin_memory: true,
                fast_init: false,
            },
            "offload_param": {
                "device": "cpu",
                "pin_memory": true,
            },
        },
        activation_checkpointing: {
            partition_activations: true,
            cpu_checkpointing: true,
            contiguous_memory_optimization: true,
            number_checkpoints: 4,
            synchronize_checkpoint_boundary: true,
            profile: false,
        },
        zero_allow_untested_optimizer: true,
        wall_clock_breakdown: false,
        step_per_print: 999999999,
    },
}
